default_agent: order_assistant
agents:
  order_assistant:
    name: order_assistant
    entrypoint: /Users/dinindu/Projects/GitHub/order-assistant/agentcore/runtime/order_assistant.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/dinindu/Projects/GitHub/order-assistant/agentcore/runtime
    aws:
      execution_role: arn:aws:iam::054671736399:role/OrderAssistantStack-AgentCoreExecutionRole416A5DC1-2pCCsoWveHOb
      execution_role_auto_create: true
      account: 054671736399
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: true
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
